name: Microdialysis
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.3
  - python=3.9
  - matplotlib=3.9
  - scikit-learn=1.6
  - numpy=2.0
  - scipy=1.13
  - ipykernel=6.29
  - statsmodels=0.14
